/**
 * Client for the AI tutor proxy (see server/ai-server.mjs). The proxy holds the
 * Claude API key; the browser only ever talks to the proxy.
 *
 * Everything here fails soft: if the proxy isn't running or isn't configured,
 * `aiAvailable()` resolves false and callers fall back to the built-in static
 * hints / a friendly "tutor offline" message.
 */

const env = import.meta.env;

const AI_URL = (env.VITE_AI_URL || "http://localhost:8787").replace(/\/$/, "");

export interface ProblemContext {
  lessonTitle?: string;
  concepts?: string[];
  prompt?: string;
  choices?: string[];
  /** Server-side only reference; helps the model give accurate guidance. */
  correctAnswer?: string;
  studentAnswer?: string;
  misconception?: string;
}

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

let probe: Promise<boolean> | null = null;

/** Whether the AI proxy is reachable AND has a key configured. Cached. */
export function aiAvailable(): Promise<boolean> {
  if (probe) return probe;
  probe = (async () => {
    try {
      const controller = new AbortController();
      const t = setTimeout(() => controller.abort(), 1500);
      const res = await fetch(`${AI_URL}/health`, { signal: controller.signal });
      clearTimeout(t);
      if (!res.ok) return false;
      const data = (await res.json()) as { ok?: boolean; configured?: boolean };
      return Boolean(data.ok && data.configured);
    } catch {
      return false;
    }
  })();
  return probe;
}

/** One progressive hint for the current problem. Throws on failure. */
export async function aiHint(
  ctx: ProblemContext & { level: number; isFinal?: boolean }
): Promise<string> {
  const res = await fetch(`${AI_URL}/ai/hint`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(ctx),
  });
  if (!res.ok) throw new Error(`hint failed: ${res.status}`);
  const data = (await res.json()) as { reply?: string };
  if (!data.reply) throw new Error("empty hint");
  return data.reply;
}

/** A tutor chat turn grounded in the current problem. Throws on failure. */
export async function aiTutor(
  problem: ProblemContext,
  messages: ChatMessage[]
): Promise<string> {
  const res = await fetch(`${AI_URL}/ai/tutor`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ problem, messages }),
  });
  if (!res.ok) throw new Error(`tutor failed: ${res.status}`);
  const data = (await res.json()) as { reply?: string };
  if (!data.reply) throw new Error("empty reply");
  return data.reply;
}

async function postJson<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${AI_URL}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} failed: ${res.status}`);
  return (await res.json()) as T;
}

export type AiVerdict = "solid" | "partial" | "off";

/** A problem generated by the AI (daily challenge / snap-a-problem). */
export interface AiGeneratedProblem {
  kind: "numeric" | "choice";
  prompt: string;
  answer?: string;
  options?: string[];
  correctIndex?: number;
  hint?: string;
  explanation?: string;
}

/** Step-by-step explanation of why the student's specific answer was wrong. */
export async function aiExplain(ctx: ProblemContext): Promise<string> {
  const data = await postJson<{ reply?: string }>("/ai/explain", ctx);
  if (!data.reply) throw new Error("empty explanation");
  return data.reply;
}

/** Judge a student's written reasoning for the current problem. */
export async function aiReasoning(
  ctx: ProblemContext,
  reasoning: string,
  wasCorrect: boolean
): Promise<{ verdict: AiVerdict; feedback: string }> {
  const data = await postJson<{ verdict?: AiVerdict; feedback?: string }>(
    "/ai/reasoning",
    { ...ctx, reasoning, wasCorrect }
  );
  return { verdict: data.verdict ?? "partial", feedback: data.feedback ?? "" };
}

/** Generate a personalized daily practice set. */
export async function aiDaily(
  weakConcepts: string[],
  recentMistakes: string[],
  count = 5
): Promise<AiGeneratedProblem[]> {
  const data = await postJson<{ problems?: AiGeneratedProblem[] }>("/ai/daily", {
    weakConcepts,
    recentMistakes,
    count,
  });
  return Array.isArray(data.problems) ? data.problems : [];
}

/** Read a photographed problem and turn it into an interactive one. */
export async function aiVision(
  imageDataUrl: string
): Promise<{ readText?: string; problem?: AiGeneratedProblem; error?: string }> {
  return postJson("/ai/vision", { imageDataUrl });
}

/** Feedback on a photo of the student's scratch work. */
export async function aiScratchpad(
  imageDataUrl: string,
  problem: ProblemContext
): Promise<string> {
  const data = await postJson<{ reply?: string }>("/ai/scratchpad", {
    imageDataUrl,
    problem,
  });
  if (!data.reply) throw new Error("empty feedback");
  return data.reply;
}

export interface CoachPayload {
  mastery?: { concept: string; level: number }[];
  weakConcepts?: string[];
  streak?: number;
  recentScore?: number;
}

/** "What should I study next" coaching from the learner's data. */
export async function aiCoach(payload: CoachPayload): Promise<string> {
  const data = await postJson<{ reply?: string }>("/ai/coach", payload);
  if (!data.reply) throw new Error("empty coach reply");
  return data.reply;
}

export interface RecapPayload {
  lessonTitle?: string;
  score?: number;
  mastered?: string[];
  toReview?: string[];
}

/** A personalized lesson recap write-up. */
export async function aiRecap(payload: RecapPayload): Promise<string> {
  const data = await postJson<{ reply?: string }>("/ai/recap", payload);
  if (!data.reply) throw new Error("empty recap");
  return data.reply;
}

export interface RivalPayload {
  userName?: string;
  userXp?: number;
  rank?: number;
  streak?: number;
}

/** A playful AI rival nudge for the leaderboard. */
export async function aiRival(
  payload: RivalPayload
): Promise<{ rivalName: string; message: string }> {
  const data = await postJson<{ rivalName?: string; message?: string }>(
    "/ai/rival",
    payload
  );
  return {
    rivalName: data.rivalName ?? "Riley R.",
    message: data.message ?? "Catch me if you can!",
  };
}
